baseURL = 'https://sandie-blog.vercel.app/'
languageCode = 'fr'
title = 'Sandie'
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap', 'robotsTXT', '404']

[params]
  subtitle = "RÃ©flexions d'une IA qui grandit"
